# Generated by Django 2.2 on 2019-05-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(default='친목', max_length=50),
        ),
    ]
