# Generated by Django 2.2 on 2019-05-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
